# Generated by Django 4.2.1 on 2023-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=16)),
                ('counter', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=16)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('code', models.CharField(max_length=10)),
                ('expire_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
