# Generated by Django 4.2.1 on 2023-06-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
