# Generated by Django 4.2.1 on 2023-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'Accepted')], default=1),
        ),
    ]
