# Generated by Django 4.2.1 on 2023-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0002_alter_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.png', null=True, upload_to='categories'),
        ),
    ]
