# Generated by Django 4.2.1 on 2023-05-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0003_alter_cart_cart_product_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='agrotech.address'),
            preserve_default=False,
        ),
    ]
