# Generated by Django 4.2.1 on 2023-07-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0002_alter_cartproduct_image_alter_order_total_price'),
        ('agrotech', '0003_alter_category_image'),
    ]

    operations = [
    ]
