# Generated by Django 4.2.1 on 2023-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0004_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattempt',
            name='email',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='email',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
