# Generated by Django 4.2.1 on 2023-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0005_alter_emailattempt_email_alter_emailcode_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255)),
                ('type_company', models.CharField(choices=[('1', 'Farmer'), ('2', 'HoReCa'), ('3', 'Manufacturer')], default='1', max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('inn', models.CharField(max_length=20)),
                ('email_company', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('owner_name', models.CharField()),
                ('owner_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('owner_phone', models.CharField()),
            ],
        ),
    ]
