# Generated by Django 4.2.1 on 2023-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotech', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner_phone',
            field=models.CharField(max_length=50),
        ),
    ]
